[package]
name = "a_plus_b_sqrt_q"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fraction = "0.14.0"
num-bigint = "0.4.4"
