[package]
name = "a_plus_b_sqrt_n"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fraction = {version = "0.15.1", features = ["with-approx"] }
num-bigint = "0.4.4"
num-traits = "0.2.18"
